package main

// writeReport turns results/*.jsonl into the measured part of results.md. Everything above
// the marker line in results.md (the hand-written findings) is kept.

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const reportMarker = "<!-- generated by `go run . -report`; do not edit below -->"

func readRuns() []RunResult {
	var out []RunResult
	f, err := os.Open(runLog)
	if err != nil {
		return nil
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 64<<20)
	for sc.Scan() {
		var r RunResult
		if json.Unmarshal(sc.Bytes(), &r) == nil {
			out = append(out, r)
		}
	}
	return out
}

func readCalib() []Calib {
	var out []Calib
	f, err := os.Open(calLog)
	if err != nil {
		return nil
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		var c Calib
		if json.Unmarshal(sc.Bytes(), &c) == nil {
			out = append(out, c)
		}
	}
	return out
}

func pct(a, b int) string {
	if b == 0 {
		return "–"
	}
	return fmt.Sprintf("%.0f%%", 100*float64(a)/float64(b))
}

type agg struct {
	n, first, valid, rounds, pass, total, prompt, output, req, peak int
	secs                                                            float64
	stops                                                           map[string]int
}

func (a *agg) add(r RunResult) {
	if a.stops == nil {
		a.stops = map[string]int{}
	}
	a.n++
	if r.FirstTryValid {
		a.first++
	}
	if r.Valid {
		a.valid++
		a.rounds += r.Rounds
	}
	a.pass += r.Pass
	a.total += r.Total
	a.prompt += r.Prompt
	a.output += r.Output
	a.req += r.Requests
	a.secs += r.Seconds
	if r.PeakPrompt > a.peak {
		a.peak = r.PeakPrompt
	}
	a.stops[r.Stop]++
}

func (a *agg) rounds1() string {
	if a.valid == 0 {
		return "–"
	}
	return fmt.Sprintf("%.1f", float64(a.rounds)/float64(a.valid))
}

func (a *agg) stopText() string {
	var ks []string
	for k, v := range a.stops {
		if k == "done" {
			continue
		}
		ks = append(ks, fmt.Sprintf("%s ×%d", k, v))
	}
	sort.Strings(ks)
	return strings.Join(ks, ", ")
}

var modelOrder = []string{"nemotron-3-ultra", "gemma4:31b", "glm-4.5-flash", "gpt-oss:120b"}

func orderedModels(runs []RunResult) []string {
	seen := map[string]bool{}
	for _, r := range runs {
		seen[r.Model] = true
	}
	var out []string
	for _, m := range modelOrder {
		if seen[m] {
			out = append(out, m)
			delete(seen, m)
		}
	}
	for m := range seen {
		out = append(out, m)
	}
	return out
}

func table(b *strings.Builder, runs []RunResult, keep func(RunResult) bool) {
	fmt.Fprintf(b, "| Model | Task | Runs | First-try valid | Valid in the end | Repair rounds (valid runs, mean) | Assertions passed | Prompt tok/run | Output tok/run | Requests/run | Peak request | Time/run | Not done |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|\n")
	for _, m := range orderedModels(runs) {
		all := &agg{}
		for _, t := range tasks {
			a := &agg{}
			for _, r := range runs {
				if r.Model == m && r.Task == t.ID && keep(r) {
					a.add(r)
					all.add(r)
				}
			}
			if a.n == 0 {
				continue
			}
			fmt.Fprintf(b, "| %s | %s | %d | %s | %s | %s | %s (%d/%d) | %d | %d | %.1f | %d | %.0f s | %s |\n", m, t.ID, a.n, pct(a.first, a.n), pct(a.valid, a.n),
				a.rounds1(), pct(a.pass, a.total), a.pass, a.total, a.prompt/a.n, a.output/a.n, float64(a.req)/float64(a.n), a.peak, a.secs/float64(a.n), a.stopText())
		}
		if all.n > 0 {
			fmt.Fprintf(b, "| **%s** | **all** | %d | **%s** | **%s** | %s | **%s** (%d/%d) | %d | %d | %.1f | %d | %.0f s | %s |\n", m, all.n, pct(all.first, all.n), pct(all.valid, all.n),
				all.rounds1(), pct(all.pass, all.total), all.pass, all.total, all.prompt/all.n, all.output/all.n, float64(all.req)/float64(all.n), all.peak, all.secs/float64(all.n), all.stopText())
		}
	}
	b.WriteString("\n")
}

func errorCats(b *strings.Builder, runs []RunResult) {
	type ex struct {
		n    int
		exs  []string
		byMd map[string]int
	}
	cats := map[string]*ex{}
	totalErr := 0
	for _, r := range runs {
		for _, w := range r.Writes {
			if w.OK {
				continue
			}
			for _, i := range w.Issues {
				if i.Warn {
					continue
				}
				e := cats[i.Cat]
				if e == nil {
					e = &ex{byMd: map[string]int{}}
					cats[i.Cat] = e
				}
				e.n++
				e.byMd[r.Model]++
				totalErr++
				if len(e.exs) < 3 && !containsPrefix(e.exs, i.Msg) {
					e.exs = append(e.exs, fmt.Sprintf("%s %s %s: `%s`", r.Model, r.Task, w.Tool, short(strings.ReplaceAll(i.Msg, "`", "'"), 260)))
				}
			}
		}
	}
	ms := orderedModels(runs)
	fmt.Fprintf(b, "| Category | Errors | %s | Examples |\n|---|---|%s---|\n", strings.Join(ms, " | "), strings.Repeat("---|", len(ms)))
	var ks []string
	for k := range cats {
		ks = append(ks, k)
	}
	sort.Slice(ks, func(i, j int) bool { return cats[ks[i]].n > cats[ks[j]].n })
	for _, k := range ks {
		e := cats[k]
		var per []string
		for _, m := range ms {
			per = append(per, fmt.Sprint(e.byMd[m]))
		}
		fmt.Fprintf(b, "| %s | %d (%s) | %s | %s |\n", k, e.n, pct(e.n, totalErr), strings.Join(per, " | "), strings.Join(e.exs, "<br>"))
	}
	b.WriteString("\n")
}

func containsPrefix(l []string, s string) bool {
	for _, x := range l {
		if strings.Contains(x, short(s, 60)) {
			return true
		}
	}
	return false
}

func checkFailures(b *strings.Builder, runs []RunResult) {
	type key struct{ m, t, c string }
	n := map[key]int{}
	why := map[key]string{}
	for _, r := range runs {
		for _, c := range r.Checks {
			if !c.OK {
				k := key{r.Model, r.Task, c.Name}
				n[k]++
				if why[k] == "" {
					why[k] = c.Why
				}
			}
		}
	}
	var ks []key
	for k := range n {
		ks = append(ks, k)
	}
	sort.Slice(ks, func(i, j int) bool {
		if ks[i].m != ks[j].m {
			return ks[i].m < ks[j].m
		}
		if ks[i].t != ks[j].t {
			return ks[i].t < ks[j].t
		}
		return ks[i].c < ks[j].c
	})
	b.WriteString("| Model | Task | Assertion | Failed runs | First reason |\n|---|---|---|---|---|\n")
	for _, k := range ks {
		fmt.Fprintf(b, "| %s | %s | %s | %d | %s |\n", k.m, k.t, k.c, n[k], short(strings.ReplaceAll(why[k], "|", "/"), 220))
	}
	b.WriteString("\n")
}

func writeReport() {
	runs := readRuns()
	cal := readCalib()
	var b strings.Builder
	b.WriteString(reportMarker + "\n\n")
	// budget
	prompt, output := 0, 0
	for _, r := range runs {
		prompt += r.Prompt
		output += r.Output
	}
	calP := 0
	for _, c := range cal {
		calP += c.Baseline + c.WithGuide + c.WithTools
	}
	smokeP := 0
	if f, err := os.Open(filepath.Join("results", "smoke.jsonl")); err == nil {
		sc := bufio.NewScanner(f)
		sc.Buffer(make([]byte, 1<<20), 16<<20)
		for sc.Scan() {
			var r RunResult
			if json.Unmarshal(sc.Bytes(), &r) == nil {
				smokeP += r.Prompt
			}
		}
		f.Close()
	}
	fmt.Fprintf(&b, "## Token budget\n\nPrompt tokens: %d in task runs + %d in calibration + %d in the smoke test = **%d of 2,000,000**. Output tokens in task runs: %d. Task runs recorded: %d.\n\n",
		prompt, calP, smokeP, prompt+calP+smokeP, output, len(runs))
	// sizes
	b.WriteString("## Guide and request sizes\n\nMeasured per model as the prompt_tokens difference against a one-line system prompt (so each model's own tokenizer and chat template).\n\n")
	b.WriteString("| Model | Guide | Guide chars | Guide tokens | Tool definitions tokens (7 tools) | Peak request (prompt tokens, any run) | Peak request, chained |\n|---|---|---|---|---|---|---|\n")
	for _, c := range cal {
		peak, peakC := 0, 0
		for _, r := range runs {
			if r.Model == c.Model && r.Guide == c.Guide {
				if !r.Chained && r.PeakPrompt > peak {
					peak = r.PeakPrompt
				}
				if r.Chained && r.PeakPrompt > peakC {
					peakC = r.PeakPrompt
				}
			}
		}
		fmt.Fprintf(&b, "| %s | %s | %d | %d | %d | %d | %d |\n", c.Model, c.Guide, c.GuideChars, c.GuideTokens, c.ToolTokens, peak, peakC)
	}
	b.WriteString("\n")
	// chained history
	var chained []RunResult
	for _, r := range runs {
		if r.Chained {
			chained = append(chained, r)
		}
	}
	if len(chained) > 0 {
		b.WriteString("Chained conversation: history block (previous turns kept in the window) at the start of each task, in characters (about chars/4 tokens), and cuts made by the SPEC 3.6 rule (8 turns or 24k tokens, cut to 3):\n\n| Model | Guide | T1 | T2 | T3 | T4 | Cuts |\n|---|---|---|---|---|---|---|\n")
		type mk struct{ m, g string }
		rows := map[mk]map[string]int{}
		cuts := map[mk]int{}
		var order []mk
		for _, r := range chained {
			k := mk{r.Model, r.Guide}
			if rows[k] == nil {
				rows[k] = map[string]int{}
				order = append(order, k)
			}
			rows[k][r.Task] = r.PeakHistoryChars
			if r.Cuts > cuts[k] {
				cuts[k] = r.Cuts
			}
		}
		for _, k := range order {
			fmt.Fprintf(&b, "| %s | %s | %d | %d | %d | %d | %d |\n", k.m, k.g, rows[k]["T1"], rows[k]["T2"], rows[k]["T3"], rows[k]["T4"], cuts[k])
		}
		b.WriteString("\n")
	}
	guidesSeen := map[string]bool{}
	for _, r := range runs {
		guidesSeen[r.Guide] = true
	}
	var gl []string
	for g := range guidesSeen {
		gl = append(gl, g)
	}
	sort.Strings(gl)
	for _, g := range gl {
		fmt.Fprintf(&b, "## Results, guide %s, single tasks (each from the reference state of the previous task)\n\n", g)
		table(&b, runs, func(r RunResult) bool { return r.Guide == g && !r.Chained })
		if len(chained) > 0 {
			fmt.Fprintf(&b, "### Guide %s, chained conversation (T1..T4 in one chat, from an empty project)\n\n", g)
			table(&b, runs, func(r RunResult) bool { return r.Guide == g && r.Chained })
		}
		fmt.Fprintf(&b, "### Guide %s: error categories (all error lines in failed write calls)\n\n", g)
		var sub []RunResult
		for _, r := range runs {
			if r.Guide == g {
				sub = append(sub, r)
			}
		}
		errorCats(&b, sub)
		fmt.Fprintf(&b, "### Guide %s: failed assertions\n\n", g)
		checkFailures(&b, sub)
	}
	// keep the hand-written part
	head := ""
	if old, err := os.ReadFile("results.md"); err == nil {
		if i := strings.Index(string(old), reportMarker); i >= 0 {
			head = string(old[:i])
		} else {
			head = string(old) + "\n"
		}
	} else {
		head = "# SPIKE-021 results\n\n"
	}
	if err := os.WriteFile("results.md", []byte(redact(head+b.String())), 0o644); err != nil {
		fmt.Fprintln(out, "cannot write results.md:", err)
		return
	}
	fmt.Fprintln(out, "results.md written")
}
