// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as id$0 from "../id/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

/**
 * Activity is one snapshot of a project's work: every Reporter's status and
 * the writer's queue (Q19a). Open is false once the project has closed.
 */
export interface Activity {
    "project": id$0.Project;
    "open": boolean;
    "leases": number;
    "work": Status[] | null;

    /**
     * project.db
     */
    "writer": store$0.WriterStats;

    /**
     * chats.db
     */
    "chats_writer": store$0.WriterStats;
}

/**
 * Damage describes a database that failed its quick_check.
 */
export interface Damage {
    /**
     * project.db or chats.db
     */
    "file": string;

    /**
     * SQLite's first problems
     */
    "problem": string;

    /**
     * the latest snapshot of that file, or "" if there is none
     */
    "snapshot": string;
}

/**
 * FolderWarning says why the data folder is a bad place for SQLite files:
 * a network drive, or a folder a sync service copies file by file, which
 * can copy the -wal file apart from its database and corrupt it (SPEC 2.1).
 */
export interface FolderWarning {
    "folder": string;
    "network": boolean;

    /**
     * OneDrive, Dropbox, iCloud Drive or Google Drive
     */
    "service"?: string;
    "text": string;
}

/**
 * Notice is a message about one project for the user.
 */
export interface Notice {
    "project": id$0.Project;
    "kind": NoticeKind;
    "text": string;
    "damage"?: Damage | null;
}

/**
 * NoticeKind says what a notice reports. Readers accept kinds they don't
 * know, since later versions add more.
 */
export enum NoticeKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * NoticeRecovered: the last session did not end cleanly; the checks
     * passed and the project works (SPEC 2.7).
     */
    NoticeRecovered = "recovered",

    /**
     * NoticeDamaged: a database failed its quick_check, so the project is
     * open read-only and the latest snapshot is offered (SPEC 2.7).
     */
    NoticeDamaged = "damaged",
};

/**
 * Status is one piece of work in a project.
 */
export interface Status {
    "id": string;

    /**
     * e.g. turn, task, run
     */
    "kind": string;

    /**
     * e.g. running, waiting, failed
     */
    "state": string;
    "started": string;
    "last_activity": string;
    "progress"?: string;
    "err"?: string;
}
