// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as chat$0 from "../chat/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as id$0 from "../id/models.js";

/**
 * Answer is the user's answer to the card or form a turn waits for.
 */
export interface Answer {
    /**
     * the card's message and part index
     */
    "message": id$0.Message;
    "index": number;

    /**
     * an approval card's option
     */
    "grant"?: chat$0.Grant;

    /**
     * Answers are a question form's, by header: the picked labels or the
     * Other text.
     */
    "answers"?: { [_ in string]?: string[] | null } | null;

    /**
     * a Deny note, or a note with the form
     */
    "note"?: string;
}

/**
 * Live is a chat's turn as it is now, for a chat opened mid-turn: the
 * stored messages come from the store, Live adds the answer still
 * streaming (Status.Streaming).
 */
export interface Live {
    "running": boolean;
    "turn": number;
    "seq": number;
    "retry"?: chat$0.Retry | null;
    "waiting"?: chat$0.Waiting | null;
    "streaming"?: id$0.Message;

    /**
     * its finished parts
     */
    "parts"?: chat$0.Part[] | null;

    /**
     * the part being streamed
     */
    "kind"?: chat$0.PartKind;

    /**
     * its text so far
     */
    "text"?: string;
}
