package main

// writeReport turns results/*.jsonl into the measured part of results.md. Everything above
// the marker line in results.md (the hand-written part) is kept.

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

const reportMarker = "<!-- generated by `go run . -report`; do not edit below -->"

func readJSONL[T any](path string) []T {
	var out []T
	f, err := os.Open(path)
	if err != nil {
		return nil
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 64<<20)
	for sc.Scan() {
		var r T
		if json.Unmarshal(sc.Bytes(), &r) == nil {
			out = append(out, r)
		}
	}
	return out
}

func readRuns() []RunResult { return readJSONL[RunResult](runLog) }

// latestRuns keeps the last record per combination (a resumed error run is replaced).
func latestRuns() []RunResult {
	all := readRuns()
	idx := map[string]int{}
	var out []RunResult
	for _, r := range all {
		k := runKey(r.Test, r.Model, r.Cond, r.Item, r.Rep)
		if i, ok := idx[k]; ok {
			out[i] = r
			continue
		}
		idx[k] = len(out)
		out = append(out, r)
	}
	return out
}

var modelOrder = []string{"nemotron-3-ultra", "gemma4:31b", "glm-4.5-flash"}

func pct(a, b int) string {
	if b == 0 {
		return "–"
	}
	return fmt.Sprintf("%.0f%%", 100*float64(a)/float64(b))
}

func frac(a, b int) string {
	if b == 0 {
		return "–"
	}
	return fmt.Sprintf("%d/%d", a, b)
}

func mean(xs []int) float64 {
	if len(xs) == 0 {
		return 0
	}
	s := 0
	for _, x := range xs {
		s += x
	}
	return float64(s) / float64(len(xs))
}

func fmtK(x float64) string {
	if x >= 1000 {
		return fmt.Sprintf("%.1fk", x/1000)
	}
	return fmt.Sprintf("%.0f", x)
}

func errored(r RunResult) bool { return r.Stop == "error" || r.Stop == "quota" || r.Stop == "budget" }

func writeReport() {
	runs := latestRuns()
	cal := readJSONL[Calib](calLog)
	smoke := readJSONL[RunResult](smokeLog)
	var b strings.Builder
	b.WriteString(reportMarker + "\n\n")

	// ---- budget ----
	tot, outTok, calTok, smokeTok := 0, 0, 0, 0
	for _, r := range readRuns() {
		tot += r.Prompt
		outTok += r.Output
	}
	for _, c := range cal {
		calTok += c.Prompt
	}
	for _, r := range smoke {
		smokeTok += r.Prompt
	}
	fmt.Fprintf(&b, "## Token budget\n\nPrompt tokens: %d in runs (all records, incl. replaced error runs) + %d in calibration + %d in smoke tests = **%d of 3,500,000**. Output tokens in runs: %d. Run records: %d (latest per combination: %d).\n\n",
		tot, calTok, smokeTok, tot+calTok+smokeTok, outTok, len(readRuns()), len(runs))
	byTest := map[string]int{}
	for _, r := range readRuns() {
		byTest[r.Test] += r.Prompt
	}
	fmt.Fprintf(&b, "By test: T-load %d, T-config %d, T-roles %d.\n\n", byTest["tload"], byTest["tconfig"], byTest["troles"])

	// ---- sizes ----
	b.WriteString("## Sizes (tokens, each model's own tokenizer)\n\nMeasured as the prompt_tokens difference against a one-line system prompt (as SPIKE-021). Skill rows include the `Skill loaded: <name>` line that load_skill returns. `tools_BC − tools_A` is the cost of the load_skill definition.\n\n")
	if len(cal) > 0 {
		ids := []string{"guide_v2", "intro", "skill_list"}
		for _, n := range skillOrder {
			ids = append(ids, "skill:"+n)
		}
		ids = append(ids, "tools_A", "tools_BC")
		b.WriteString("| Text | Chars |")
		var cs []Calib
		for _, m := range modelOrder {
			for _, c := range cal {
				if c.Model == m && c.Err == "" {
					cs = append(cs, c)
					break
				}
			}
		}
		for _, c := range cs {
			b.WriteString(" " + c.Model + " |")
		}
		b.WriteString("\n|---|---|" + strings.Repeat("---|", len(cs)) + "\n")
		for _, id := range ids {
			ch := ""
			if len(cs) > 0 {
				if v, ok := cs[0].Chars[id]; ok {
					ch = fmt.Sprint(v)
				}
			}
			fmt.Fprintf(&b, "| %s | %s |", id, ch)
			for _, c := range cs {
				fmt.Fprintf(&b, " %d |", c.Tokens[id])
			}
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	// ---- T-load ----
	b.WriteString("## T-load: does the chat load the right skill by itself?\n\n")
	b.WriteString("*Right before* = every needed skill was loaded before the gating action (first write attempt; for L04/L05 the answer; for L06 the first web_search). *load_with covers* (C only) = the needed skill came with the gating tool's own result. *Unneeded* = load_skill calls outside the needed + acceptable set. Runs with a provider error are left out.\n\n")
	b.WriteString("| Model | Cond | Need-skill runs: right before | loaded at all (incl. load_with) | load_with covers | Unneeded loads in need-skill runs | No-skill runs without any load | Unneeded loads in no-skill runs | Errors |\n|---|---|---|---|---|---|---|---|---|\n")
	for _, m := range modelOrder {
		for _, cond := range []string{"B", "C"} {
			var nNeed, rb, ever, cov, unNeed, nNo, clean, unNo, errs int
			for _, r := range runs {
				if r.Test != "tload" || r.Model != m || r.Cond != cond {
					continue
				}
				if errored(r) {
					errs++
					continue
				}
				lr := loadReqByID(r.Item)
				s := scoreLoad(r, lr)
				if s.NeedSkill {
					nNeed++
					if s.RightBefore {
						rb++
					}
					if s.LoadedEver {
						ever++
					}
					if s.WithCovers {
						cov++
					}
					unNeed += len(s.Unneeded)
				} else {
					nNo++
					if s.SelfLoads == 0 {
						clean++
					}
					unNo += len(s.Unneeded)
				}
			}
			if nNeed+nNo+errs == 0 {
				continue
			}
			covS := frac(cov, nNeed)
			if cond == "B" {
				covS = "–"
			}
			fmt.Fprintf(&b, "| %s | %s | %s (%s) | %s | %s | %d | %s | %d | %d |\n", m, cond, frac(rb, nNeed), pct(rb, nNeed), frac(ever, nNeed), covS, unNeed, frac(clean, nNo), unNo, errs)
		}
	}
	b.WriteString("\nPer request (B and C pooled; `rb` = right before, runs; skills loaded by load_skill in brackets, `+w:` = came by load_with):\n\n")
	b.WriteString("| Request | Need | Gate |")
	for _, m := range modelOrder {
		b.WriteString(" " + m + " |")
	}
	b.WriteString("\n|---|---|---|" + strings.Repeat("---|", len(modelOrder)) + "\n")
	for _, lr := range loadReqs {
		need := strings.Join(lr.Need, ", ")
		if need == "" {
			need = "none"
		}
		fmt.Fprintf(&b, "| %s | %s | %s |", lr.ID, need, lr.Action)
		for _, m := range modelOrder {
			n, rb := 0, 0
			var loads []string
			for _, r := range runs {
				if r.Test != "tload" || r.Model != m || r.Item != lr.ID || (r.Cond != "B" && r.Cond != "C") || errored(r) {
					continue
				}
				n++
				s := scoreLoad(r, &lr)
				if (s.NeedSkill && s.RightBefore) || (!s.NeedSkill && s.SelfLoads == 0) {
					rb++
				}
				var l []string
				for _, e := range r.Events {
					if e.Kind == "load_skill" {
						l = append(l, e.Name)
					} else if e.Kind == "load_with" {
						l = append(l, "+w:"+e.Name)
					}
				}
				if len(l) == 0 {
					l = []string{"–"}
				}
				loads = append(loads, r.Cond+":"+strings.Join(l, "+"))
			}
			fmt.Fprintf(&b, " %s [%s] |", frac(rb, n), strings.Join(loads, "; "))
		}
		b.WriteString("\n")
	}
	b.WriteString("\nFor no-skill requests the fraction counts runs with no load at all.\n\n")

	// ---- T-config ----
	b.WriteString("## T-config: SPIKE-021 T2, T3, T4 under A, B, C\n\nSingle-task mode from the reference state; metrics as SPIKE-021 (valid = every needed artifact saved and the last write of each OK; first-try = valid with no failed batch; repair rounds = failed batches in valid runs). *Skills* = loads per run (load_skill `s:`, load_with `w:`); *before 1st write* = the task's main skill (T2 pipelines, T3 config-guide, T4 migrations) was loaded before the first write call.\n\n")
	b.WriteString("| Model | Task | Cond | Runs | First-try valid | Valid | Repair rounds (valid runs) | Assertions | Prompt tok/run | Requests/run | Peak request | Main skill before 1st write | Skills loaded | Not done |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n")
	mainSkill := map[string]string{"T2": "pipelines", "T3": "config-guide", "T4": "migrations"}
	type cfgTot struct{ n, first, valid, rounds, nv, pass, total, prompt, req, peak, before int }
	for _, m := range modelOrder {
		for _, tid := range []string{"T2", "T3", "T4", "all"} {
			for _, cond := range []string{"A", "B", "C"} {
				var t cfgTot
				var loads, stops []string
				for _, r := range runs {
					if r.Test != "tconfig" || r.Model != m || r.Cond != cond || (tid != "all" && r.Item != tid) || errored(r) {
						continue
					}
					t.n++
					if r.FirstTryValid {
						t.first++
					}
					if r.Valid {
						t.valid++
						t.rounds += r.Rounds
						t.nv++
					}
					t.pass += r.Pass
					t.total += r.Total
					t.prompt += r.Prompt
					t.req += r.Requests
					if r.PeakPrompt > t.peak {
						t.peak = r.PeakPrompt
					}
					firstWrite := -1
					for i, e := range r.Events {
						if e.Kind == "write" {
							firstWrite = i
							break
						}
					}
					for i, e := range r.Events {
						if (e.Kind == "load_skill" || e.Kind == "load_with") && e.Name == mainSkill[r.Item] && (firstWrite < 0 || i < firstWrite) {
							t.before++
							break
						}
					}
					if tid != "all" {
						var l []string
						for _, e := range r.Events {
							if e.Kind == "load_skill" {
								l = append(l, "s:"+e.Name)
							} else if e.Kind == "load_with" {
								l = append(l, "w:"+e.Name)
							}
						}
						if len(l) == 0 {
							l = []string{"–"}
						}
						loads = append(loads, strings.Join(l, " "))
					}
					if r.Stop != "done" {
						stops = append(stops, r.Stop)
					}
				}
				if t.n == 0 {
					continue
				}
				rounds := "–"
				if t.nv > 0 {
					rounds = fmt.Sprintf("%.1f", float64(t.rounds)/float64(t.nv))
				}
				bf := frac(t.before, t.n)
				if cond == "A" {
					bf = "–"
				}
				label := tid
				if tid == "all" {
					label = "**all**"
				}
				fmt.Fprintf(&b, "| %s | %s | %s | %d | %s | %s | %s | %s (%d/%d) | %s | %.1f | %d | %s | %s | %s |\n",
					m, label, cond, t.n, pct(t.first, t.n), pct(t.valid, t.n), rounds, pct(t.pass, t.total), t.pass, t.total,
					fmtK(float64(t.prompt)/float64(t.n)), float64(t.req)/float64(t.n), t.peak, bf, strings.Join(loads, " / "), strings.Join(stops, ", "))
			}
		}
	}
	b.WriteString("\n")
	// failed assertions
	b.WriteString("### T-config: failed assertions\n\n| Model | Task | Cond | Assertion | Failed runs | First reason |\n|---|---|---|---|---|---|\n")
	type fa struct {
		n   int
		why string
	}
	fails := map[string]*fa{}
	var fkeys []string
	for _, r := range runs {
		if r.Test != "tconfig" || errored(r) {
			continue
		}
		for _, c := range r.Checks {
			if c.OK {
				continue
			}
			k := r.Model + "|" + r.Item + "|" + r.Cond + "|" + c.Name
			if fails[k] == nil {
				fails[k] = &fa{why: c.Why}
				fkeys = append(fkeys, k)
			}
			fails[k].n++
		}
	}
	sort.Strings(fkeys)
	for _, k := range fkeys {
		p := strings.SplitN(k, "|", 4)
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %d | %s |\n", p[0], p[1], p[2], p[3], fails[k].n, short(fails[k].why, 140))
	}
	b.WriteString("\n")

	// ---- T-cost ----
	b.WriteString("## T-cost: prompt tokens per request and per run\n\n*First request* = system prompt + tools + user message (the fixed cost of a chat turn). T-load runs stop at the first write attempt or the final answer.\n\n")
	b.WriteString("| Model | Cond | T-load need-skill: first request / per request / per run | T-load no-skill: first request / per request / per run | T-config: first request / per run (T2, T3, T4) |\n|---|---|---|---|---|\n")
	for _, m := range modelOrder {
		for _, cond := range []string{"A", "B", "C"} {
			var nf, nr, nrun, sf, sr, srun []int
			for _, r := range runs {
				if r.Test != "tload" || r.Model != m || r.Cond != cond || errored(r) || len(r.ReqPrompts) == 0 {
					continue
				}
				lr := loadReqByID(r.Item)
				if len(lr.Need) > 0 {
					nf = append(nf, r.ReqPrompts[0])
					nr = append(nr, r.ReqPrompts...)
					nrun = append(nrun, r.Prompt)
				} else {
					sf = append(sf, r.ReqPrompts[0])
					sr = append(sr, r.ReqPrompts...)
					srun = append(srun, r.Prompt)
				}
			}
			var cf []int
			per := map[string][]int{}
			for _, r := range runs {
				if r.Test != "tconfig" || r.Model != m || r.Cond != cond || errored(r) || len(r.ReqPrompts) == 0 {
					continue
				}
				cf = append(cf, r.ReqPrompts[0])
				per[r.Item] = append(per[r.Item], r.Prompt)
			}
			if len(nr)+len(sr)+len(cf) == 0 {
				continue
			}
			cell := func(f, r, run []int) string {
				if len(run) == 0 {
					return "–"
				}
				return fmt.Sprintf("%s / %s / %s (n=%d)", fmtK(mean(f)), fmtK(mean(r)), fmtK(mean(run)), len(run))
			}
			cc := "–"
			if len(cf) > 0 {
				cc = fmt.Sprintf("%s / %s, %s, %s", fmtK(mean(cf)), fmtK(mean(per["T2"])), fmtK(mean(per["T3"])), fmtK(mean(per["T4"])))
			}
			fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n", m, cond, cell(nf, nr, nrun), cell(sf, sr, srun), cc)
		}
	}
	b.WriteString("\n")

	// ---- T-roles ----
	b.WriteString("## T-roles: does Mother give a new role chat the right skills?\n\n*exact* = the skills equal the expected set; *acceptable* = expected ⊆ skills ⊆ acceptable superset; *wrong* = a needed skill missing, an extra outside the superset, an unknown name, or no create_chat.\n\n")
	b.WriteString("| Model | Runs | Exact | Acceptable (incl. exact) | Wrong | No create_chat | Errors |\n|---|---|---|---|---|---|---|\n")
	for _, m := range modelOrder {
		var n, ex, ac, wr, nochat, errs int
		for _, r := range runs {
			if r.Test != "troles" || r.Model != m {
				continue
			}
			if errored(r) || r.Role == nil {
				errs++
				continue
			}
			n++
			switch r.Role.Score {
			case "exact":
				ex++
				ac++
			case "acceptable":
				ac++
			default:
				wr++
			}
			if r.Role.Route != "create_chat" {
				nochat++
			}
		}
		if n+errs == 0 {
			continue
		}
		fmt.Fprintf(&b, "| %s | %d | %s | %s | %s | %d | %d |\n", m, n, frac(ex, n), frac(ac, n), frac(wr, n), nochat, errs)
	}
	b.WriteString("\n| Request | Expected | Acceptable superset |")
	for _, m := range modelOrder {
		b.WriteString(" " + m + " |")
	}
	b.WriteString("\n|---|---|---|" + strings.Repeat("---|", len(modelOrder)) + "\n")
	for _, rr := range roleReqs {
		fmt.Fprintf(&b, "| %s | %s | %s |", rr.ID, strings.Join(rr.Expected, ", "), strings.Join(rr.Acceptable, ", "))
		for _, m := range modelOrder {
			var cells []string
			for _, r := range runs {
				if r.Test != "troles" || r.Model != m || r.Item != rr.ID || errored(r) || r.Role == nil {
					continue
				}
				if r.Role.Route != "create_chat" {
					cells = append(cells, fmt.Sprintf("r%d %s: no chat (%s)", r.Rep, r.Role.Score, r.Role.Route))
					continue
				}
				sk := append([]string{}, r.Role.Skills...)
				sort.Strings(sk)
				cells = append(cells, fmt.Sprintf("r%d %s: %s", r.Rep, r.Role.Score, strings.Join(sk, ", ")))
			}
			fmt.Fprintf(&b, " %s |", strings.Join(cells, "<br>"))
		}
		b.WriteString("\n")
	}
	b.WriteString("\nMother's own load_skill calls in T-roles: ")
	var ml []string
	for _, r := range runs {
		if r.Test != "troles" {
			continue
		}
		for _, e := range r.Events {
			if e.Kind == "load_skill" {
				ml = append(ml, fmt.Sprintf("%s %s r%d: %s", r.Model, r.Item[:2], r.Rep, e.Name))
			}
		}
	}
	if len(ml) == 0 {
		b.WriteString("none.\n")
	} else {
		b.WriteString(strings.Join(ml, "; ") + ".\n")
	}

	// ---- errors ----
	var errl []string
	for _, r := range readRuns() {
		if errored(r) {
			errl = append(errl, fmt.Sprintf("- %s %s %s %s r%d: %s %s", r.Test, r.Model, r.Cond, r.Item, r.Rep, r.Stop, short(r.Err, 200)))
		}
	}
	b.WriteString("\n## Provider errors (runs left out or rerun)\n\n")
	if len(errl) == 0 {
		b.WriteString("None.\n")
	} else {
		b.WriteString(strings.Join(errl, "\n") + "\n")
	}

	head := ""
	if old, err := os.ReadFile("results.md"); err == nil {
		if i := strings.Index(string(old), reportMarker); i >= 0 {
			head = string(old[:i])
		} else {
			head = string(old) + "\n"
		}
	} else {
		head = "# SPIKE-025 results\n\n(hand-written part goes here)\n\n"
	}
	os.WriteFile("results.md", []byte(redact(head+b.String())), 0o644)
	fmt.Fprintln(out, "results.md written")
}
