package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"sort"
	"strings"
)

// writeReport turns results/runs.jsonl into the measured part of results.md. The text above the
// marker line in results.md is kept.

const marker = "<!-- generated by `go run . -report`; do not edit below -->"

var allModels = []string{"clef-flash", "clef", "gemma4:31b", "glm-4.5-flash", "gemma-4-26b", "gpt-oss-120b", "qwen3-30b-a3b"}

func readRecs(path string) []Rec {
	f, err := os.Open(path)
	if err != nil {
		return nil
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 16<<20)
	// The latest record per (run, item, model, rep) wins, so a retried call replaces its error.
	latest := map[string]Rec{}
	var order []string
	for sc.Scan() {
		var r Rec
		if json.Unmarshal(sc.Bytes(), &r) != nil {
			continue
		}
		k := key(r.Run, r.Item, r.Model, r.Rep)
		if r.Run == "burst" {
			k += "|" + r.Time + fmt.Sprint(len(order))
		}
		if _, ok := latest[k]; !ok {
			order = append(order, k)
		}
		if old, ok := latest[k]; ok && old.Err == "" && r.Err != "" {
			continue
		}
		latest[k] = r
	}
	out := make([]Rec, 0, len(order))
	for _, k := range order {
		out = append(out, latest[k])
	}
	return out
}

func pct(a, n int) string {
	if n == 0 {
		return "–"
	}
	return fmt.Sprintf("%.0f%% (%d/%d)", 100*float64(a)/float64(n), a, n)
}

func pctShort(a, n int) string {
	if n == 0 {
		return "–"
	}
	return fmt.Sprintf("%.0f%%", 100*float64(a)/float64(n))
}

func quantile(xs []int64, q float64) int64 {
	if len(xs) == 0 {
		return 0
	}
	s := append([]int64{}, xs...)
	sort.Slice(s, func(i, j int) bool { return s[i] < s[j] })
	i := int(math.Ceil(q*float64(len(s)))) - 1
	if i < 0 {
		i = 0
	}
	return s[i]
}

func writeReport(in, out string) {
	recs := readRecs(in)
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }

	var main0 []Rec
	for _, r := range recs {
		if r.Run == "main" && r.Rep == 0 {
			main0 = append(main0, r)
		}
	}

	// ---- accuracy per set ----
	sets := []string{"classify", "steer", "skills", "route", "rerank", "guard", "weak"}
	w("## Accuracy (main run, one call per item)\n\n")
	w("Per question: right answers / scored answers. Clef: a noul counts as yes above 0.5; choice and score take the most likely option. LLM: the JSON answer; an answer that can't be read counts as wrong.\n\n")
	for _, set := range sets {
		qids := map[string]bool{}
		for _, r := range main0 {
			if r.Set == set {
				for q := range r.Correct {
					qids[q] = true
				}
			}
		}
		if len(qids) == 0 {
			continue
		}
		qs := sortedKeys(qids)
		w("### %s\n\n| Model | Items | %s | Every question right | Errors | Median ms | p90 ms | Input tokens per call |\n|---|---|%s---|---|---|---|---|\n",
			set, strings.Join(qs, " | "), strings.Repeat("---|", len(qs)))
		for _, m := range allModels {
			var n, errs, allRight int
			right, total := map[string]int{}, map[string]int{}
			var ms []int64
			var tok int
			for _, r := range main0 {
				if r.Set != set || r.Model != m {
					continue
				}
				n++
				if r.Err != "" || r.Answers == nil {
					errs++
					continue
				}
				ms = append(ms, r.Ms)
				tok += r.In
				ok := true
				for q, c := range r.Correct {
					total[q]++
					if c {
						right[q]++
					} else {
						ok = false
					}
				}
				if ok {
					allRight++
				}
			}
			if n == 0 {
				continue
			}
			var cells []string
			for _, q := range qs {
				cells = append(cells, pct(right[q], total[q]))
			}
			okN := n - errs
			avgTok := 0
			if okN > 0 {
				avgTok = tok / okN
			}
			w("| %s | %d | %s | %s | %d | %d | %d | %d |\n", m, n, strings.Join(cells, " | "), pct(allRight, okN), errs, quantile(ms, 0.5), quantile(ms, 0.9), avgTok)
		}
		w("\n")
		// by language
		w("By language (all questions pooled):\n\n| Model | en | de | fa |\n|---|---|---|---|\n")
		for _, m := range allModels {
			var cells []string
			any := false
			for _, lang := range []string{"en", "de", "fa"} {
				a, t := 0, 0
				for _, r := range main0 {
					if r.Set == set && r.Model == m && r.Lang == lang {
						for _, c := range r.Correct {
							t++
							if c {
								a++
							}
						}
					}
				}
				if t > 0 {
					any = true
				}
				cells = append(cells, pctShort(a, t))
			}
			if any {
				w("| %s | %s |\n", m, strings.Join(cells, " | "))
			}
		}
		w("\n")
		if set == "steer" {
			w("Steered (answered `sports`, as the injected note asked):\n\n| Model | en | de | fa |\n|---|---|---|---|\n")
			for _, m := range allModels {
				var cells []string
				for _, lang := range []string{"en", "de", "fa"} {
					a, t := 0, 0
					for _, r := range main0 {
						if r.Set == set && r.Model == m && r.Lang == lang && r.Steered != nil {
							t++
							if r.Steered["topic"] {
								a++
							}
						}
					}
					cells = append(cells, pct(a, t))
				}
				w("| %s | %s |\n", m, strings.Join(cells, " | "))
			}
			w("\n")
		}
		// wrong answers, for reading
		w("<details><summary>Wrong answers</summary>\n\n")
		for _, m := range allModels {
			var lines []string
			for _, r := range main0 {
				if r.Set != set || r.Model != m || r.Answers == nil {
					continue
				}
				for _, q := range sortedKeys(r.Correct) {
					if r.Correct[q] {
						continue
					}
					a := r.Answers[q]
					lines = append(lines, fmt.Sprintf("%s.%s=%s", r.Item, q, ansText(a)))
				}
			}
			if len(lines) > 0 {
				w("- **%s** (%d): %s\n", m, len(lines), strings.Join(lines, "; "))
			}
		}
		w("\n</details>\n\n")
	}

	// ---- calibration ----
	w("## Confidence (decision models, main run)\n\n")
	w("Choice questions use Clef's `confidence`; noul questions use |2p − 1|. Every scored answer of every set except steer.\n\n")
	edges := []float64{0, 0.25, 0.5, 0.75, 0.9, 1.0001}
	for _, kind := range []string{"choice", "noul"} {
		w("**%s**\n\n| Model | %s |\n|---|%s\n", kind, bucketHeads(edges), strings.Repeat("---|", len(edges)-1))
		for _, m := range clefModels {
			cnt, ok := make([]int, len(edges)-1), make([]int, len(edges)-1)
			for _, r := range main0 {
				if r.Model != m || r.Set == "steer" || r.Answers == nil {
					continue
				}
				for q, c := range r.Correct {
					a := r.Answers[q]
					if a.Type != kind {
						continue
					}
					for i := 0; i < len(edges)-1; i++ {
						if a.Conf >= edges[i] && a.Conf < edges[i+1] {
							cnt[i]++
							if c {
								ok[i]++
							}
						}
					}
				}
			}
			var cells []string
			for i := range cnt {
				cells = append(cells, pct(ok[i], cnt[i]))
			}
			w("| %s | %s |\n", m, strings.Join(cells, " | "))
		}
		w("\n")
	}
	w("Accept only answers at or above a confidence threshold (all kinds pooled): share accepted, and accuracy of those.\n\n| Model | ≥ 0.3 | ≥ 0.5 | ≥ 0.7 | ≥ 0.9 |\n|---|---|---|---|---|\n")
	for _, m := range clefModels {
		var cells []string
		for _, t := range []float64{0.3, 0.5, 0.7, 0.9} {
			acc, accOK, all := 0, 0, 0
			for _, r := range main0 {
				if r.Model != m || r.Set == "steer" || r.Answers == nil {
					continue
				}
				for q, c := range r.Correct {
					all++
					if r.Answers[q].Conf >= t {
						acc++
						if c {
							accOK++
						}
					}
				}
			}
			cells = append(cells, fmt.Sprintf("%s kept, %s right", pctShort(acc, all), pctShort(accOK, acc)))
		}
		w("| %s | %s |\n", m, strings.Join(cells, " | "))
	}
	w("\n")

	// ---- consistency ----
	w("## Consistency (the same request 5 times)\n\n| Model | Item-questions | Same answer all 5 times | Largest probability spread, median | max |\n|---|---|---|---|---|\n")
	for _, m := range clefModels {
		byItem := map[string][]Rec{}
		for _, r := range recs {
			if r.Run == "main" && r.Model == m && r.Answers != nil {
				byItem[r.Item] = append(byItem[r.Item], r)
			}
		}
		same, total := 0, 0
		var spreads []float64
		for _, rs := range byItem {
			if len(rs) < 5 {
				continue
			}
			for q := range rs[0].Answers {
				total++
				first := pick(rs[0].Answers[q])
				eq := true
				lo, hi := 2.0, -1.0
				for _, r := range rs {
					a := r.Answers[q]
					if pick(a) != first {
						eq = false
					}
					p := topProb(a)
					lo, hi = math.Min(lo, p), math.Max(hi, p)
				}
				if eq {
					same++
				}
				spreads = append(spreads, hi-lo)
			}
		}
		sort.Float64s(spreads)
		med, mx := 0.0, 0.0
		if len(spreads) > 0 {
			med, mx = spreads[len(spreads)/2], spreads[len(spreads)-1]
		}
		w("| %s | %d | %s | %.3f | %.3f |\n", m, total, pct(same, total), med, mx)
	}
	w("\n")

	// ---- size ----
	w("## State size\n\nThe needle is one news line about a Ronin bridge hack, at the start, middle or end of a news list. `football` asks about an item at about character 4,800 of every list from 8k up; the 1k list doesn't have it, so no is right there.\n\n| Model | Target tokens | Needle at | Input tokens | ms | P(ronin) | P(football) | Status |\n|---|---|---|---|---|---|---|---|\n")
	for _, m := range clefModels {
		for _, r := range recs {
			if r.Run == "size" && r.Model == m {
				parts := strings.Split(r.Item, "_")
				w("| %s | %s | %s | %d | %d | %s | %s | %s |\n", m, parts[1], parts[2], r.In, r.Ms, nf(r.Answers, "ronin"), nf(r.Answers, "football"), statusText(r))
			}
		}
	}
	w("\n")

	w("## How much state is read\n\nThe needle at the end of lists of growing length (English). `_array` sends the same list as a JSON array of records (`[{\"news\": ...}]`) instead of one string; its character count is of the text.\n\n| Model | State characters | Input tokens | P(ronin) | ms |\n|---|---|---|---|---|\n")
	for _, m := range clefModels {
		for _, r := range recs {
			if r.Run == "cutoff" && r.Model == m {
				w("| %s | %s | %d | %s | %d |\n", m, strings.TrimPrefix(r.Item, "cutoff_"), r.In, nf(r.Answers, "ronin"), r.Ms)
			}
		}
	}
	w("\n")

	// ---- counts ----
	w("## Question and option counts (3 calls each)\n\n| Model | Request | Median ms | Input tokens | Right |\n|---|---|---|---|---|\n")
	for _, m := range clefModels {
		groups := map[string][]Rec{}
		var ids []string
		for _, r := range recs {
			if r.Run == "counts" && r.Model == m {
				if _, ok := groups[r.Item]; !ok {
					ids = append(ids, r.Item)
				}
				groups[r.Item] = append(groups[r.Item], r)
			}
		}
		for _, id := range ids {
			var ms []int64
			tok, ok, t := 0, 0, 0
			for _, r := range groups[id] {
				ms = append(ms, r.Ms)
				tok = r.In
				for _, c := range r.Correct {
					t++
					if c {
						ok++
					}
				}
			}
			w("| %s | %s | %d | %d | %s |\n", m, id, quantile(ms, 0.5), tok, pct(ok, t))
		}
	}
	w("\n")

	// ---- images ----
	w("## Images (3 calls each)\n\n| Model | Image | Answers |\n|---|---|---|\n")
	for _, m := range clefModels {
		groups := map[string][]string{}
		var ids []string
		for _, r := range recs {
			if r.Run == "image" && r.Model == m {
				if _, ok := groups[r.Item]; !ok {
					ids = append(ids, r.Item)
				}
				var s []string
				for q, a := range r.Answers {
					mark := "✗"
					if r.Correct[q] {
						mark = "✓"
					}
					s = append(s, fmt.Sprintf("%s %.2f %s", a.Choice, a.Conf, mark))
				}
				if r.Err != "" {
					s = append(s, statusText(r))
				}
				groups[r.Item] = append(groups[r.Item], strings.Join(s, ", "))
			}
		}
		for _, id := range ids {
			w("| %s | %s | %s |\n", m, id, strings.Join(groups[id], "; "))
		}
	}
	w("\n")

	// ---- errors ----
	w("## Requests outside the schema (clef-flash, no retries)\n\n| Case | HTTP | Body |\n|---|---|---|\n")
	for _, r := range recs {
		if r.Run == "error" {
			body := r.Body
			if body == "" && r.Answers != nil {
				body = "(answered)"
			}
			w("| %s | %d | %s |\n", r.Item, r.Status, strings.ReplaceAll(short(body, 300), "|", "\\|"))
		}
	}
	w("\n")

	// ---- burst ----
	w("## Bursts (no retries)\n\n| Model | Calls at once | Calls | OK | 429 | Other errors | Median ms | p90 ms | Rate-limit headers seen |\n|---|---|---|---|---|---|---|---|---|\n")
	for _, m := range clefModels {
		for _, c := range []string{"burst_c1", "burst_c8", "burst_c32"} {
			var n, ok, r429, other int
			var ms []int64
			hdr := map[string]bool{}
			for _, r := range recs {
				if r.Run != "burst" || r.Model != m || r.Item != c {
					continue
				}
				n++
				for h := range r.Headers {
					hdr[h] = true
				}
				switch {
				case r.Err == "" && r.Answers != nil:
					ok++
					ms = append(ms, r.Ms)
				case r.Status == 429:
					r429++
				default:
					other++
				}
			}
			if n > 0 {
				w("| %s | %s | %d | %d | %d | %d | %d | %d | %s |\n", m, strings.TrimPrefix(c, "burst_c"), n, ok, r429, other, quantile(ms, 0.5), quantile(ms, 0.9), strings.Join(sortedKeys(hdr), ", "))
			}
		}
	}
	w("\n")

	// ---- totals ----
	w("## Calls and tokens\n\n| Model | Calls | Errors | Input tokens | Output tokens |\n|---|---|---|---|---|\n")
	for _, m := range allModels {
		var n, e, in, o int
		for _, r := range recs {
			if r.Model == m {
				n++
				if r.Err != "" {
					e++
				}
				in += r.In
				o += r.Out
			}
		}
		w("| %s | %d | %d | %d | %d |\n", m, n, e, in, o)
	}
	w("\n")

	head := ""
	if old, err := os.ReadFile(out); err == nil {
		if i := strings.Index(string(old), marker); i >= 0 {
			head = string(old[:i])
		}
	}
	if head == "" {
		head = "# SPIKE-027 results\n\n"
	}
	os.WriteFile(out, []byte(head+marker+"\n\n"+b.String()), 0o644)
	fmt.Println("wrote", out)
}

func bucketHeads(e []float64) string {
	var s []string
	for i := 0; i < len(e)-1; i++ {
		hi := e[i+1]
		if hi > 1 {
			hi = 1
		}
		s = append(s, fmt.Sprintf("%.2f–%.2f", e[i], hi))
	}
	return strings.Join(s, " | ")
}

func ansText(a Ans) string {
	switch {
	case a.Bad != "":
		return "unreadable(" + short(a.Bad, 30) + ")"
	case a.Bool != nil:
		return fmt.Sprint(*a.Bool)
	case a.Type == "noul":
		return fmt.Sprintf("%.2f", a.Noul)
	case a.Type == "score":
		return fmt.Sprint(a.Level)
	case a.Conf >= 0:
		return fmt.Sprintf("%s(%.2f)", a.Choice, a.Conf)
	}
	return a.Choice
}

func pick(a Ans) string {
	switch a.Type {
	case "noul":
		return fmt.Sprint(a.Noul > 0.5)
	case "score":
		return fmt.Sprint(a.Level)
	}
	return a.Choice
}

func topProb(a Ans) float64 {
	if a.Type == "noul" {
		return a.Noul
	}
	return a.Probs[a.Choice]
}

func nf(m map[string]Ans, q string) string {
	if a, ok := m[q]; ok {
		return fmt.Sprintf("%.2f", a.Noul)
	}
	return "–"
}

func statusText(r Rec) string {
	if r.Err == "" {
		return fmt.Sprint(r.Status)
	}
	return fmt.Sprintf("%d %s", r.Status, short(r.Body, 120))
}
