package main

// report.go writes the measured part of results.md (everything below the marker) from
// results/runs.jsonl. The part above the marker is written by hand.

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

const marker = "<!-- measured: generated by `go run . -report`; do not edit below -->"

var testNames = map[string]string{
	"1": "Quick part first",
	"2": "Finish turn",
	"3": "Message during a turn",
	"4": "No false background work",
	"5": "Cost (peak prompt <= 8,000 tokens per request)",
	"6": "Delegation (Mother chat)",
}

type cell struct{ pass, fail, na int }

func (c cell) String() string {
	n := c.pass + c.fail
	if n == 0 {
		if c.na > 0 {
			return fmt.Sprintf("n/a (%d)", c.na)
		}
		return "-"
	}
	s := fmt.Sprintf("%.0f%% (%d/%d)", 100*float64(c.pass)/float64(n), c.pass, n)
	if c.na > 0 {
		s += fmt.Sprintf(", n/a %d", c.na)
	}
	return s
}

func (c *cell) add(st string) {
	switch st {
	case "pass":
		c.pass++
	case "fail":
		c.fail++
	case "na", "skip":
		c.na++
	}
}

func modelsOf(runs []*RunRec) []string {
	order := []string{"nemotron-3-ultra", "gemma4:31b", "glm-4.5-flash"}
	seen := map[string]bool{}
	for _, r := range runs {
		seen[r.Model] = true
	}
	var out []string
	for _, m := range order {
		if seen[m] {
			out = append(out, m)
			delete(seen, m)
		}
	}
	for m := range seen {
		out = append(out, m)
	}
	return out
}

func writeReport(runs []*RunRec, scens []*Scenario) {
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }
	models := modelsOf(runs)
	conds := []string{"rule", "base"}
	var ok, v2 []*RunRec
	errs := map[string]int{}
	for _, r := range runs {
		if r.Err != "" {
			errs[r.Model+" "+short(r.Err, 90)]++
			continue
		}
		if r.Cond == "rule2" {
			v2 = append(v2, r)
			continue
		}
		ok = append(ok, r)
	}
	w("\n## Measured results\n\n")
	nErr := 0
	for _, n := range errs {
		nErr += n
	}
	w("Generated from `results/runs.jsonl` (%d runs: %d with and without the rule, %d follow-up runs with delegation guidance v2, %d with a provider error, left out of the rates). n = runs; n/a = the test's precondition was not met (e.g. no finish turn because no background work was started or the result was taken by polling).\n\n", len(runs), len(ok), len(v2), nErr)
	// runs per model and condition
	w("### Runs\n\n| Model | rule runs | base runs | prompt tokens (all runs incl. follow-up) | output tokens |\n|---|---|---|---|---|\n")
	for _, m := range models {
		n := map[string]int{}
		pt, ot := 0, 0
		for _, r := range runs {
			if r.Model == m {
				n[r.Cond]++
				pt += r.Prompt
				ot += r.Output
			}
		}
		w("| %s | %d | %d | %d | %d |\n", m, n["rule"], n["base"], pt, ot)
	}
	if len(errs) > 0 {
		w("\nRuns stopped by errors:\n")
		var ks []string
		for k := range errs {
			ks = append(ks, k)
		}
		sort.Strings(ks)
		for _, k := range ks {
			w("- %d x %s\n", errs[k], k)
		}
	}
	// per test
	w("\n### Pass rate per test\n\nA run passes a test when every assertion of that test passes.\n\n")
	w("| Test | Model | with rule | without rule |\n|---|---|---|---|\n")
	for _, tid := range []string{"1", "2", "3", "4", "5", "6"} {
		for _, m := range models {
			cs := map[string]*cell{"rule": {}, "base": {}}
			for _, r := range ok {
				if r.Model != m {
					continue
				}
				if st, has := r.TestStatus[tid]; has {
					cs[r.Cond].add(st)
				}
			}
			w("| %s %s | %s | %s | %s |\n", tid, testNames[tid], m, cs["rule"], cs["base"])
		}
		// all models
		cs := map[string]*cell{"rule": {}, "base": {}}
		for _, r := range ok {
			if st, has := r.TestStatus[tid]; has {
				cs[r.Cond].add(st)
			}
		}
		w("| %s | **all** | **%s** | **%s** |\n", tid, cs["rule"], cs["base"])
	}
	// per assertion type within each test
	w("\n### Pass rate per assertion\n\n| Test | Assertion | Model | with rule | without rule |\n|---|---|---|---|---|\n")
	type key struct{ test, typ string }
	var keys []key
	seenK := map[key]bool{}
	for _, r := range ok {
		for _, a := range r.Asserts {
			k := key{a.Test, a.Type}
			if !seenK[k] {
				seenK[k] = true
				keys = append(keys, k)
			}
		}
	}
	sort.Slice(keys, func(i, j int) bool {
		if keys[i].test != keys[j].test {
			return keys[i].test < keys[j].test
		}
		return keys[i].typ < keys[j].typ
	})
	for _, k := range keys {
		for _, m := range models {
			cs := map[string]*cell{"rule": {}, "base": {}}
			for _, r := range ok {
				if r.Model != m {
					continue
				}
				for _, a := range r.Asserts {
					if a.Test == k.test && a.Type == k.typ {
						cs[r.Cond].add(a.Status)
					}
				}
			}
			w("| %s | %s | %s | %s | %s |\n", k.test, k.typ, m, cs["rule"], cs["base"])
		}
	}
	// per scenario
	w("\n### Per scenario\n\nEach cell: runs that passed all of the scenario's non-info assertions / runs.\n\n| Scenario | Tests |")
	for _, m := range models {
		w(" %s rule | %s base |", m, m)
	}
	w("\n|---|---|")
	for range models {
		w("---|---|")
	}
	w("\n")
	for _, s := range scens {
		w("| %s | %s |", s.ID, strings.Join(s.Tests, ","))
		for _, m := range models {
			for _, c := range conds {
				p, n := 0, 0
				for _, r := range ok {
					if r.Model == m && r.Scenario == s.ID && r.Cond == c {
						n++
						all := true
						for _, st := range r.TestStatus {
							if st == "fail" {
								all = false
							}
						}
						if all {
							p++
						}
					}
				}
				if n == 0 {
					w(" - |")
				} else {
					w(" %d/%d |", p, n)
				}
			}
		}
		w("\n")
	}
	// tokens
	w("\n### Test 5: tokens per scenario\n\nMean prompt tokens per run (all requests of all turns), with rule / without rule, and the difference.\n\n| Scenario |")
	for _, m := range models {
		w(" %s |", m)
	}
	w(" all |\n|---|")
	for range models {
		w("---|")
	}
	w("---|\n")
	mean := func(f func(r *RunRec) bool, g func(r *RunRec) int) (float64, int) {
		s, n := 0, 0
		for _, r := range ok {
			if f(r) {
				s += g(r)
				n++
			}
		}
		if n == 0 {
			return 0, 0
		}
		return float64(s) / float64(n), n
	}
	prompt := func(r *RunRec) int { return r.Prompt }
	fmtPair := func(a, b float64, na, nb int) string {
		if na == 0 || nb == 0 {
			return "-"
		}
		d := 0.0
		if b > 0 {
			d = 100 * (a - b) / b
		}
		return fmt.Sprintf("%.0f / %.0f (%+.0f%%)", a, b, d)
	}
	for _, s := range scens {
		w("| %s |", s.ID)
		for _, m := range append(append([]string{}, models...), "") {
			a, na := mean(func(r *RunRec) bool { return r.Scenario == s.ID && r.Cond == "rule" && (m == "" || r.Model == m) }, prompt)
			bb, nb := mean(func(r *RunRec) bool { return r.Scenario == s.ID && r.Cond == "base" && (m == "" || r.Model == m) }, prompt)
			w(" %s |", fmtPair(a, bb, na, nb))
		}
		w("\n")
	}
	w("| **mean per run** |")
	for _, m := range append(append([]string{}, models...), "") {
		a, na := mean(func(r *RunRec) bool { return r.Cond == "rule" && (m == "" || r.Model == m) }, prompt)
		bb, nb := mean(func(r *RunRec) bool { return r.Cond == "base" && (m == "" || r.Model == m) }, prompt)
		w(" **%s** |", fmtPair(a, bb, na, nb))
	}
	w("\n\nOther cost figures, with rule / without rule:\n\n| Model | first request prompt tokens | requests per run | output tokens per run | turns per run | status polls per run | real seconds per run |\n|---|---|---|---|---|---|---|\n")
	for _, m := range models {
		f := func(c string) func(r *RunRec) bool {
			return func(r *RunRec) bool { return r.Model == m && r.Cond == c }
		}
		cols := []func(r *RunRec) int{
			func(r *RunRec) int { return r.FirstPrompt },
			func(r *RunRec) int { return r.Requests },
			func(r *RunRec) int { return r.Output },
			func(r *RunRec) int { return len(r.Turns) },
			func(r *RunRec) int { return r.Polls },
			func(r *RunRec) int { return int(r.Seconds) },
		}
		w("| %s |", m)
		for _, g := range cols {
			a, _ := mean(f("rule"), g)
			bb, _ := mean(f("base"), g)
			w(" %.1f / %.1f |", a, bb)
		}
		w("\n")
	}
	// failure reasons
	w("\n### Most common failure reasons\n\n| Assertion | Model | Cond | Why (first 110 chars) | Count |\n|---|---|---|---|---|\n")
	type fk struct{ typ, model, cond, why string }
	fc := map[fk]int{}
	for _, r := range ok {
		for _, a := range r.Asserts {
			if a.Status == "fail" && a.Test != "info" {
				why := a.Why
				if strings.HasPrefix(why, "5-gram") || strings.HasPrefix(why, "quick part at") || strings.HasPrefix(why, "peak prompt") {
					why = strings.SplitN(why, " ", 3)[0] + " " + strings.SplitN(why, " ", 3)[1]
				}
				fc[fk{a.Type, r.Model, r.Cond, short(why, 110)}]++
			}
		}
	}
	var fks []fk
	for k := range fc {
		fks = append(fks, k)
	}
	sort.Slice(fks, func(i, j int) bool {
		if fks[i].typ != fks[j].typ {
			return fks[i].typ < fks[j].typ
		}
		return fc[fks[i]] > fc[fks[j]]
	})
	for _, k := range fks {
		w("| %s | %s | %s | %s | %d |\n", k.typ, k.model, k.cond, strings.ReplaceAll(k.why, "|", "/"), fc[k])
	}
	// follow-up: delegation guidance v2
	if len(v2) > 0 {
		w("\n### Follow-up: delegation guidance v2 (condition rule2)\n\nSame scenarios, rule plus `prompts/delegation_v2.md` instead of `prompts/delegation.md`. Each cell: runs that passed test 6 / runs.\n\n| Scenario | Model | guidance v2 | guidance v1 (rule) | none (base) | v2 prompt tokens per run |\n|---|---|---|---|---|---|\n")
		scenSeen := map[string]bool{}
		for _, r := range v2 {
			scenSeen[r.Scenario] = true
		}
		all := append(append([]*RunRec{}, ok...), v2...)
		for _, s := range scens {
			if !scenSeen[s.ID] {
				continue
			}
			for _, m := range models {
				row := []string{}
				for _, c := range []string{"rule2", "rule", "base"} {
					p, n := 0, 0
					for _, r := range all {
						if r.Scenario == s.ID && r.Model == m && r.Cond == c && r.Err == "" {
							n++
							if r.TestStatus["6"] != "fail" {
								p++
							}
						}
					}
					row = append(row, fmt.Sprintf("%d/%d", p, n))
				}
				a, _ := mean(func(r *RunRec) bool { return false }, prompt)
				s2, n2 := 0, 0
				for _, r := range v2 {
					if r.Scenario == s.ID && r.Model == m {
						s2 += r.Prompt
						n2++
					}
				}
				if n2 > 0 {
					a = float64(s2) / float64(n2)
				}
				w("| %s | %s | %s | %s | %s | %.0f |\n", s.ID, m, row[0], row[1], row[2], a)
			}
		}
		w("\nFailures under v2:\n\n")
		for _, r := range v2 {
			for _, a := range r.Asserts {
				if a.Status == "fail" && a.Test != "info" {
					w("- %s %s r%d: %s: %s\n", r.Scenario, r.Model, r.Rep, a.Type, strings.ReplaceAll(short(a.Why, 140), "|", "/"))
				}
			}
		}
	}
	// write
	old, _ := os.ReadFile("results.md")
	head := string(old)
	if i := strings.Index(head, marker); i >= 0 {
		head = head[:i]
	} else if head == "" {
		head = "# SPIKE-023 results\n\n"
	}
	os.WriteFile("results.md", []byte(strings.TrimRight(head, "\n")+"\n\n"+marker+"\n"+redact(b.String())), 0o644)
	fmt.Fprintln(out, "results.md written")
}
