// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Typed IDs, so the compiler catches a chat ID passed as a project ID (Q8).
 * TypeScript sees plain strings.
 */
export type Approval = string;

/**
 * Typed IDs, so the compiler catches a chat ID passed as a project ID (Q8).
 * TypeScript sees plain strings.
 */
export type Chat = string;

/**
 * Typed IDs, so the compiler catches a chat ID passed as a project ID (Q8).
 * TypeScript sees plain strings.
 */
export type Message = string;

/**
 * Typed IDs, so the compiler catches a chat ID passed as a project ID (Q8).
 * TypeScript sees plain strings.
 */
export type Project = string;

/**
 * Source says who did something: "app", "user", "auto", or "<kind>:<id>"
 * such as "message:01J…" or "run:01J…" (SPEC 2.5). A kind may gain an ID
 * later, so readers accept both forms.
 */
export enum Source {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Sources without an ID.
     *
     * the app itself, e.g. the Mother chat
     */
    SourceApp = "app",

    /**
     * the person using the app
     */
    SourceUser = "user",

    /**
     * the Auto approval level (SPEC 8.8)
     */
    SourceAuto = "auto",
};
