// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Level is how tight memory is.
 */
export enum Level {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OK = "ok",

    /**
     * under LowBytes free, or the OS warns
     */
    Low = "low",

    /**
     * under StopBytes free, or the OS is critical
     */
    Critical = "critical",
};

/**
 * Reading is one reading. Free is 0 where the OS gives only a level
 * (macOS). Total is what Free is out of: the commit limit (RAM plus page
 * files) on Windows, the physical memory elsewhere.
 */
export interface Reading {
    /**
     * bytes the OS can still hand out
     */
    "free": number;

    /**
     * bytes Free is out of
     */
    "total": number;
    "level": Level;
}
