// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ApprovalSettings {
    /**
     * strict, standard, auto (SPEC 8.8)
     */
    "default_level": string;
}

/**
 * ContextSettings size the history window (SPEC 3.6).
 */
export interface ContextSettings {
    "history_min_turns": number;
    "history_max_turns": number;
    "history_max_tokens": number;
    "tool_preview_tokens": number;
    "turn_trim_ratio": number;
}

/**
 * LLMSettings are the limits for model calls (SPEC 7.6, 8.3) and the model
 * aliases (SPEC 3.9).
 */
export interface LLMSettings {
    /**
     * background calls; chats never wait
     */
    "max_parallel_calls": number;

    /**
     * provider name → background calls; a local Ollama defaults to 1
     */
    "provider_max_parallel_calls": { [_ in string]?: number } | null;
    "max_background_tasks_per_chat": number;
    "max_subagents_per_chat": number;
    "turn_max_requests": number;
    "system_turn_max_requests": number;
    "system_turn_max_tokens": number;

    /**
     * alias → model, e.g. "default"
     */
    "models": { [_ in string]?: string } | null;

    /**
     * Providers are the connected providers by name, e.g. "gemini" or
     * "zai". Their keys are in the OS keychain as "provider:<name>".
     */
    "providers": { [_ in string]?: ProviderSettings } | null;
}

/**
 * ModelSettings is a model that is on.
 */
export interface ModelSettings {
    "id": string;

    /**
     * tokens; for models the catalog doesn't know
     */
    "context"?: number;
}

/**
 * Problem is a setting that was ignored: unknown, of the wrong type or out
 * of range. The default is used instead.
 */
export interface Problem {
    /**
     * e.g. "context.history_min_turns"
     */
    "path": string;
    "line": number;
    "msg": string;
}

/**
 * ProviderSettings is one connected provider (SPEC 3.9).
 */
export interface ProviderSettings {
    /**
     * anthropic, openai, gemini, openai_compatible or ollama
     */
    "kind": string;

    /**
     * BaseURL is needed for openai_compatible; "" means the kind's own. It
     * may hold placeholders such as {account_id}, whose values are kept in
     * the keychain like the key, not in this file.
     */
    "base_url"?: string;

    /**
     * Models are the models that are on, as the provider names them.
     */
    "models": ModelSettings[] | null;
}

export interface SchedulerSettings {
    "max_parallel_runs": number;
}

/**
 * Settings are the user settings in config.yaml (SPEC 2.1).
 */
export interface Settings {
    /**
     * "" means ~/Jenab
     */
    "data_folder": string;
    "context": ContextSettings;
    "llm": LLMSettings;
    "scheduler": SchedulerSettings;
    "approvals": ApprovalSettings;
    "ui": UISettings;
    "updates": UpdateSettings;
    "dev_tools": boolean;
}

export interface UISettings {
    /**
     * light, dark, system (SPEC 5.11)
     */
    "theme": string;
}

export interface UpdateSettings {
    /**
     * automatic, notify, off (SPEC 2.8)
     */
    "mode": string;

    /**
     * stable, beta
     */
    "channel": string;
}
