// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as chat$0 from "../../../../amir-saatchi/jenab/internal/chat/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as project$0 from "../../../../amir-saatchi/jenab/internal/project/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "chat:delta": chat$0.Delta;
            "chat:part": chat$0.PartDone;
            "chat:status": chat$0.Status;
            "project:activity": project$0.Activity;
            "project:notice": project$0.Notice;
        }
    }
}
