// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as chat$0 from "../chat/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as id$0 from "../id/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Hit is one message that matched, with a snippet of its text.
 */
export interface Hit {
    "chat": id$0.Chat;
    "message": id$0.Message;
    "turn": number;
    "role": chat$0.Role;
    "created_at": string;
    "snippet": string;
}

/**
 * SearchResult is the hits, best first for a word search and newest first
 * for a substring scan.
 */
export interface SearchResult {
    "hits": Hit[] | null;

    /**
     * Stopped is set when a substring scan reached its time limit; older
     * messages may match too.
     */
    "stopped": boolean;
}

/**
 * WriterStats is a snapshot for the runtime panel (Q19a).
 */
export interface WriterStats {
    /**
     * requests waiting
     */
    "Interactive": number;
    "Background": number;

    /**
     * a request is running
     */
    "Busy": boolean;

    /**
     * how long it has run
     */
    "Age": time$0.Duration;

    /**
     * requests finished since open
     */
    "Done": number;
    "LastError": string;
}
