// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as id$0 from "../id/models.js";

/**
 * Approval is an approval card (SPEC 8.8). Kind and Target name what is
 * approved, as _jenab_approvals stores it: a host, a script's hash.
 */
export interface Approval {
    "id": id$0.Approval;

    /**
     * host, migration, starlark, connection, mcp, command
     */
    "kind": string;
    "target": string;

    /**
     * what is asked
     */
    "ask": string;

    /**
     * one line from the agent
     */
    "why"?: string;
    "risk": string;
    "details"?: string;

    /**
     * e.g. "Allow for this project", "Deny"
     */
    "options": ApprovalOption[] | null;

    /**
     * The answer, once given.
     */
    "answer"?: Grant;

    /**
     * a Deny note, or the message written instead
     */
    "note"?: string;

    /**
     * "user", or "auto" for the Auto level
     */
    "by"?: id$0.Source;
    "answered_at"?: string | null;

    /**
     * Stopped: Stop or the project's close ended the wait, without an answer.
     */
    "stopped"?: boolean;
}

/**
 * ApprovalOption is one button of an approval card.
 */
export interface ApprovalOption {
    "label": string;
    "grant": Grant;
}

/**
 * Chat is one row of chats.db's chats table (SPEC 2.3).
 */
export interface Chat {
    "id": id$0.Chat;
    "kind": Kind;
    "title": string;

    /**
     * set by the user, so it is never generated again
     */
    "title_fixed": boolean;

    /**
     * at most 500 tokens (8.6)
     */
    "role": string;

    /**
     * 8.9
     */
    "skills": string[] | null;

    /**
     * 3.9; new chats use "default"
     */
    "model": string;
    "default_page": string;

    /**
     * "app" (the Mother chat), "user", or "message:<id>" of Mother's create_chat call
     */
    "created_by": id$0.Source;
    "created_at": string;
    "archived": boolean;
}

/**
 * Delta is streamed text for a part still in progress. At most one per 16 ms
 * per chat (Q17).
 */
export interface Delta {
    "project": id$0.Project;
    "chat": id$0.Chat;
    "seq": number;
    "message": id$0.Message;

    /**
     * the part's index in the message
     */
    "part": number;

    /**
     * text or thinking
     */
    "kind": PartKind;

    /**
     * new text since the last delta
     */
    "text": string;
}

/**
 * Grant is what an approval option gives.
 */
export enum Grant {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * this call only
     */
    GrantOnce = "once",

    /**
     * kept for the project; the target isn't asked for again
     */
    GrantAlways = "always",
    GrantDeny = "deny",
};

/**
 * Image is an image stored in the bucket (4.7); the bytes are never in a part.
 */
export interface Image {
    "ref": string;
    "mime": string;
    "alt"?: string;
}

/**
 * Kind is the kind of chat (SPEC 8.6).
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * one per project; can be cleared, not archived or deleted
     */
    KindMother = "mother",
    KindChat = "chat",
};

/**
 * Message is one message with its parts (SPEC 2.3). A turn is one user
 * message plus everything the agent does until it replies.
 */
export interface Message {
    "id": id$0.Message;
    "chat": id$0.Chat;
    "turn": number;
    "role": Role;

    /**
     * assistant messages only
     */
    "model"?: string;
    "usage": Usage;
    "created_at": string;
    "parts": Part[] | null;
}

/**
 * Notice is a short note from the app to the agent, shown in the chat.
 */
export interface Notice {
    "kind": NoticeKind;
    "text": string;
}

/**
 * NoticeKind says what a notice reports. Readers accept kinds they don't
 * know, since later versions add more.
 */
export enum NoticeKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * starts a finish turn (8.3)
     */
    NoticeTaskFinished = "task_finished",

    /**
     * a scheduled run (3.1)
     */
    NoticeRunFinished = "run_finished",

    /**
     * the user opened a page or changed its filters (5.9)
     */
    NoticePageOpened = "page_opened",

    /**
     * between cuts (3.6)
     */
    NoticeMemoryChanged = "memory_changed",

    /**
     * 8.8
     */
    NoticeApprovalLevel = "approval_level",

    /**
     * a turn ended after a failed save (10)
     */
    NoticeEarlyStop = "early_stop",

    /**
     * a provider error stopped the turn; the card offers Retry (8.3)
     */
    NoticeTurnFailed = "turn_failed",

    /**
     * the answer hit the output limit, was refused or was empty (8.3)
     */
    NoticeAnswerCut = "answer_cut",

    /**
     * the chip; in the tool message, so the model doesn't read it (8.9)
     */
    NoticeSkillLoaded = "skill_loaded",
};

/**
 * Option is one choice; an Other field is always added by the UI.
 */
export interface Option {
    "label": string;
    "description"?: string;
    "recommended"?: boolean;
}

/**
 * Part is one part of a message: Kind plus exactly one matching field (Q7).
 * JSON, the generated TypeScript and the database stay plain this way.
 */
export interface Part {
    "kind": PartKind;
    "text"?: Text | null;
    "thinking"?: Thinking | null;
    "tool_call"?: ToolCall | null;
    "tool_result"?: ToolResult | null;
    "image"?: Image | null;
    "notice"?: Notice | null;
    "approval"?: Approval | null;
    "question"?: Question | null;
}

/**
 * PartDone is a finished part, as it was written to chats.db.
 */
export interface PartDone {
    "project": id$0.Project;
    "chat": id$0.Chat;
    "seq": number;
    "message": id$0.Message;
    "index": number;
    "part": Part;
}

/**
 * PartKind is the type column of message_parts (SPEC 2.3).
 */
export enum PartKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PartText = "text",
    PartThinking = "thinking",
    PartToolCall = "tool_call",
    PartToolResult = "tool_result",
    PartImage = "image",
    PartNotice = "notice",
    PartApproval = "approval",
    PartQuestion = "question",
};

/**
 * Question is a question form from ask_user (SPEC 8.8).
 */
export interface Question {
    "questions": QuestionItem[] | null;

    /**
     * Answers maps a header to the picked labels or the Other text, once
     * answered. A message written instead goes in Note.
     */
    "answers"?: { [_ in string]?: string[] | null } | null;
    "note"?: string;
    "answered_at"?: string | null;

    /**
     * as for Approval
     */
    "stopped"?: boolean;
}

/**
 * QuestionItem is one question of a form.
 */
export interface QuestionItem {
    "header": string;
    "question": string;
    "options": Option[] | null;
    "multi"?: boolean;
}

/**
 * Retry is a turn's wait before it tries a failed request again, so the
 * chat can show "gemini is rate limited, retrying in 42 s" with *Retry now*
 * and *Cancel* (8.3). The failed try's streamed text is dropped (see
 * Status.Streaming).
 */
export interface Retry {
    /**
     * the connection's name
     */
    "provider": string;

    /**
     * rate_limited, overloaded or transport
     */
    "kind": string;

    /**
     * when the next try starts, in UTC
     */
    "at": string;
}

/**
 * Role is who wrote a message.
 */
export enum Role {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RoleUser = "user",
    RoleAssistant = "assistant",
    RoleTool = "tool",
};

/**
 * State is what a chat is doing.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateIdle = "idle",

    /**
     * a turn is running
     */
    StateWorking = "working",

    /**
     * a turn waits for an approval or an answer (8.8)
     */
    StateWaiting = "waiting",
};

/**
 * Status is a chat's state, with its running background tasks.
 */
export interface Status {
    "project": id$0.Project;
    "chat": id$0.Chat;
    "seq": number;
    "state": State;

    /**
     * background tasks still running (8.3)
     */
    "tasks": number;

    /**
     * set when State is waiting
     */
    "waiting"?: Waiting | null;

    /**
     * set while a turn waits to retry a request (8.3)
     */
    "retry"?: Retry | null;

    /**
     * Streaming is the answer being streamed now, not yet stored.
     */
    "streaming"?: id$0.Message;
}

/**
 * Text is text the model or the user wrote.
 */
export interface Text {
    "text": string;

    /**
     * cut off by Stop and kept (8.3)
     */
    "stopped"?: boolean;
}

/**
 * Thinking is the model's thinking. It is sent back to the provider
 * unchanged, signature included, before its tool calls (SPEC 3.8).
 */
export interface Thinking {
    "text": string;
    "signature"?: string;

    /**
     * a redacted block's opaque data; Text is empty then
     */
    "redacted"?: string;
}

/**
 * ToolCall is a call the model asked for.
 */
export interface ToolCall {
    "id": string;
    "name": string;
    "args": json$0.RawMessage;

    /**
     * Extra is a provider's data for the call, sent back unchanged, such as
     * Gemini's extra_content with its thought signature (SPEC 3.8). It is raw
     * JSON kept as a string: encoding/json compacts and escapes a RawMessage,
     * and a string comes back byte for byte.
     */
    "extra"?: string;
}

/**
 * ToolResult is a tool's answer to one call. A large output is stored in the
 * bucket: Ref is its key and Text the preview (SPEC 3.7).
 */
export interface ToolResult {
    "call_id": string;
    "text": string;
    "ref"?: string;

    /**
     * also "cancelled by user" after Stop (8.3)
     */
    "is_error"?: boolean;
}

/**
 * Usage is the token count of one model response (SPEC 3.8). Cache reads and
 * writes are kept apart, since they are priced apart.
 */
export interface Usage {
    /**
     * not read from the cache
     */
    "input": number;
    "output": number;
    "cache_read": number;
    "cache_write": number;
}

/**
 * Waiting points at the card or form a turn waits for, for the bar above the
 * composer and the chat list's badge (8.8).
 */
export interface Waiting {
    "message": id$0.Message;

    /**
     * the part's index in the message
     */
    "index": number;

    /**
     * approval or question
     */
    "kind": PartKind;

    /**
     * what is asked, in one line
     */
    "text": string;
}
