// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BucketService lists a project's files (SPEC 4). The files themselves
 * load from /objects/<project_id>/<key>, never through a binding (Q31).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as id$0 from "../id/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * List lists the files and folders directly under prefix.
 */
export function List(p: id$0.Project, prefix: string, after: string): $CancellablePromise<$models.ObjectPage> {
    return $Call.ByID(1671358197, p, prefix, after);
}

/**
 * Versions lists a file's versions, the newest first.
 */
export function Versions(p: id$0.Project, key: string): $CancellablePromise<$models.ObjectVersion[] | null> {
    return $Call.ByID(3106450688, p, key);
}
