// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService is the chats of a project (SPEC 8.3, 8.6, 8.8).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "../agent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as chat$0 from "../chat/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as id$0 from "../id/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Answer answers the approval card or question form the turn waits for.
 */
export function Answer(p: id$0.Project, c: id$0.Chat, a: agent$0.Answer): $CancellablePromise<void> {
    return $Call.ByID(890716563, p, c, a);
}

/**
 * Archive archives the chat, or brings it back.
 */
export function Archive(p: id$0.Project, c: id$0.Chat, archived: boolean): $CancellablePromise<void> {
    return $Call.ByID(2331934025, p, c, archived);
}

/**
 * Clear removes the chat's messages and session notes (8.6).
 */
export function Clear(p: id$0.Project, c: id$0.Chat): $CancellablePromise<void> {
    return $Call.ByID(131829078, p, c);
}

/**
 * Create adds a chat for the user, with an optional title and role.
 */
export function Create(p: id$0.Project, title: string, role: string): $CancellablePromise<chat$0.Chat> {
    return $Call.ByID(3667413041, p, title, role);
}

/**
 * Delete removes the chat.
 */
export function Delete(p: id$0.Project, c: id$0.Chat): $CancellablePromise<void> {
    return $Call.ByID(1333517942, p, c);
}

/**
 * List returns the project's chats, the Mother chat first.
 */
export function List(p: id$0.Project): $CancellablePromise<$models.ChatItem[] | null> {
    return $Call.ByID(3816194061, p);
}

/**
 * Messages returns the chat's turns from through to, for scrolling up;
 * to 0 means up to the last turn.
 */
export function Messages(p: id$0.Project, c: id$0.Chat, $from: number, to: number): $CancellablePromise<chat$0.Message[] | null> {
    return $Call.ByID(2994867441, p, c, $from, to);
}

/**
 * Rename sets the chat's title; a title the user sets is never generated
 * again. It returns the title as stored.
 */
export function Rename(p: id$0.Project, c: id$0.Chat, title: string): $CancellablePromise<string> {
    return $Call.ByID(2756809567, p, c, title);
}

/**
 * Retry tries the failed request again (*Retry*, *Retry now*).
 */
export function Retry(p: id$0.Project, c: id$0.Chat): $CancellablePromise<void> {
    return $Call.ByID(1186012941, p, c);
}

/**
 * Search searches the project's chat history.
 */
export function Search(p: id$0.Project, q: $models.SearchRequest): $CancellablePromise<store$0.SearchResult> {
    return $Call.ByID(303103325, p, q);
}

/**
 * Send adds the user's message; the turn's progress comes as events.
 * Pictures come with the composer's attachments (P1-15).
 */
export function Send(p: id$0.Project, c: id$0.Chat, text: string): $CancellablePromise<id$0.Message> {
    return $Call.ByID(1560175187, p, c, text);
}

/**
 * SetLevel sets the project's approval level from the chat's chip (8.8):
 * strict, standard or auto.
 */
export function SetLevel(p: id$0.Project, c: id$0.Chat, level: string): $CancellablePromise<void> {
    return $Call.ByID(2685545655, p, c, level);
}

/**
 * SetModel sets the chat's model from the model picker (3.9).
 */
export function SetModel(p: id$0.Project, c: id$0.Chat, model: string): $CancellablePromise<void> {
    return $Call.ByID(809488964, p, c, model);
}

/**
 * SetRole sets the chat's role; the model sees it from the next cut (8.6).
 */
export function SetRole(p: id$0.Project, c: id$0.Chat, role: string): $CancellablePromise<void> {
    return $Call.ByID(3207183699, p, c, role);
}

/**
 * Snapshot returns the chat with its last SnapshotTurns turns. Live is
 * read first, so a part that finishes meanwhile is in Messages.
 */
export function Snapshot(p: id$0.Project, c: id$0.Chat): $CancellablePromise<$models.ChatSnapshot> {
    return $Call.ByID(1796865569, p, c);
}

/**
 * Stop ends the chat's turn (*Stop*, 8.3).
 */
export function Stop(p: id$0.Project, c: id$0.Chat): $CancellablePromise<void> {
    return $Call.ByID(1081880097, p, c);
}
