// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DevService is the developer tools' read-only view (SPEC 8.4): the turn
 * inspector and the runtime panel. It is bound only when the developer
 * tools are on. Every text it returns has its secrets redacted (6.7).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as id$0 from "../id/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Block is the text of one context block of a request, as the provider
 * got it.
 */
export function Block(p: id$0.Project, c: id$0.Chat, n: number, request: number, block: number): $CancellablePromise<string> {
    return $Call.ByID(3393643117, p, c, n, request, block);
}

/**
 * Log returns the last log lines that contain match; "" returns the last
 * lines.
 */
export function Log(match: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2347167590, match);
}

/**
 * Providers lists each provider's calls, limits and pause.
 */
export function Providers(): $CancellablePromise<$models.ProviderStatus[] | null> {
    return $Call.ByID(1192645654);
}

/**
 * Runtime is a snapshot of the open projects, the LLM-call slots and the
 * providers. It opens nothing.
 */
export function Runtime(): $CancellablePromise<$models.Runtime> {
    return $Call.ByID(3299443784);
}

/**
 * Turn is one recorded turn.
 */
export function Turn(p: id$0.Project, c: id$0.Chat, n: number): $CancellablePromise<$models.TurnView> {
    return $Call.ByID(3117144299, p, c, n);
}

/**
 * Turns lists the recorded turns, newest first. They are kept in memory
 * from the start of the app: the last 100.
 */
export function Turns(): $CancellablePromise<$models.TurnItem[] | null> {
    return $Call.ByID(333838152);
}
