// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DevService is the developer tools' read-only view (SPEC 8.4). It is
 * bound only when the developer tools are on; P1-17 adds the turn
 * inspector and the rest of the runtime panel.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as id$0 from "../id/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "../project/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Activity is a project's work and its writers' queues.
 */
export function Activity(p: id$0.Project): $CancellablePromise<project$0.Activity> {
    return $Call.ByID(1065108937, p);
}

/**
 * Log returns the last log lines that contain match; "" returns the last
 * lines.
 */
export function Log(match: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2347167590, match);
}

/**
 * Providers lists each provider's calls, limits and pause.
 */
export function Providers(): $CancellablePromise<$models.ProviderStatus[] | null> {
    return $Call.ByID(1192645654);
}
