// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "../agent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as chat$0 from "../chat/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as id$0 from "../id/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "../project/models.js";

/**
 * ChatItem is a row of the chat list.
 */
export interface ChatItem {
    "chat": chat$0.Chat;

    /**
     * as chat:status sends it
     */
    "state": chat$0.State;

    /**
     * the newest message; nil without messages
     */
    "last_activity"?: string | null;
}

/**
 * ChatSnapshot is a chat as it is now (Q32): its last turns, the sequence
 * number they are current at, and the turn still running. Events with a
 * lower Seq are already in it.
 */
export interface ChatSnapshot {
    "chat": chat$0.Chat;
    "messages": chat$0.Message[] | null;

    /**
     * the first turn in Messages; older ones come from Messages
     */
    "from": number;
    "seq": number;

    /**
     * the answer still streaming, a wait or a retry
     */
    "live": agent$0.Live;
}

/**
 * ConnectRequest is the *Connect* form.
 */
export interface ConnectRequest {
    "name": string;
    "kind": string;
    "base_url": string;
    "key": string;

    /**
     * values for the base URL's placeholders
     */
    "fields": { [_ in string]?: string } | null;
}

/**
 * ConnectResult is what *Connect* found and saved.
 */
export interface ConnectResult {
    "provider": string;

    /**
     * the models turned on
     */
    "models": number;

    /**
     * Other are listed models the catalog doesn't know, off by default.
     */
    "other": string[] | null;

    /**
     * NoModelList: the provider lists no models, so they are added by hand.
     */
    "no_model_list": boolean;
    "view": SettingsView;
}

/**
 * ModelGroup is one connected provider with its models that are on, for
 * the model picker (SPEC 3.9).
 */
export interface ModelGroup {
    "provider": string;
    "kind": string;
    "models": ModelItem[] | null;
}

/**
 * ModelItem is a model that is on.
 */
export interface ModelItem {
    /**
     * "provider/model", as chats.model stores it
     */
    "ref": string;

    /**
     * the catalog's name, else the model ID
     */
    "name": string;

    /**
     * "default" or "fast" when they point at it
     */
    "aliases": string[] | null;
}

/**
 * ModelOption is a model that can be turned on or off.
 */
export interface ModelOption {
    "id": string;

    /**
     * the catalog's or the provider's name, else the ID
     */
    "name": string;

    /**
     * in llm.providers.<name>.models
     */
    "on": boolean;

    /**
     * tokens: the setting, the catalog or the provider's; 0 if unknown
     */
    "context": number;

    /**
     * in the catalog
     */
    "known": boolean;
}

/**
 * Notification is a desktop notification for a chat that waits for the
 * user. A click shows the window and sends app:open with the chat.
 */
export interface Notification {
    "project": id$0.Project;
    "chat": id$0.Chat;
    "title": string;
    "body": string;
}

/**
 * Object is a file in the bucket.
 */
export interface $Object {
    "key": string;
    "sha256": string;
    "mime": string;
    "size": number;
    "version": number;

    /**
     * upload, http, pipeline, agent or tool
     */
    "source": string;
    "source_url"?: string;
    "created_by": id$0.Source;
    "updated_at": string;
    "expires"?: string | null;
}

/**
 * ObjectPage is one page of a folder.
 */
export interface ObjectPage {
    "objects": $Object[] | null;

    /**
     * ending in "/"
     */
    "folders": string[] | null;

    /**
     * pass as after for the next page; "" at the end
     */
    "next": string;
}

/**
 * ObjectVersion is one version of a file.
 */
export interface ObjectVersion {
    "version": number;
    "sha256": string;
    "size": number;
    "created_by": id$0.Source;
    "created_at": string;
}

/**
 * Open is a chat to show, after its notification was clicked.
 */
export interface Open {
    "project": id$0.Project;
    "chat": id$0.Chat;
}

/**
 * OpenedProject is a project as the app shell needs it.
 */
export interface OpenedProject {
    "id": id$0.Project;
    "name": string;

    /**
     * the Mother chat, opened first (8.6)
     */
    "mother": id$0.Chat;

    /**
     * the approval level (8.8)
     */
    "level": string;

    /**
     * Damage is set when the project is open read-only after damage (2.7).
     */
    "damage"?: project$0.Damage | null;
}

/**
 * PresetItem is a well-known provider for the *Connect* form (SPEC 3.9).
 */
export interface PresetItem {
    /**
     * the suggested connection name
     */
    "id": string;
    "name": string;
    "kind": string;

    /**
     * "" means the kind's own
     */
    "base_url": string;

    /**
     * the base URL's placeholders, e.g. account_id
     */
    "fields": string[] | null;

    /**
     * a local Ollama needs no key
     */
    "no_key": boolean;

    /**
     * Ollama answers on this machine
     */
    "running": boolean;
}

/**
 * ProjectItem is a row of the project list.
 */
export interface ProjectItem {
    "id": id$0.Project;
    "name": string;
    "folder": string;
    "pinned": boolean;

    /**
     * nil if never opened
     */
    "last_opened"?: string | null;
    "created_at": string;
}

/**
 * ProviderModels is one provider's models for *Settings → Models* (SPEC
 * 3.9).
 */
export interface ProviderModels {
    "provider": string;
    "kind": string;

    /**
     * Models are the catalog models the provider lists (Anthropic, OpenAI,
     * Gemini), or every listed model (OpenAI-compatible, Ollama), then the
     * models that are on but not listed.
     */
    "models": ModelOption[] | null;

    /**
     * Other are listed models the catalog doesn't know (*Other models*).
     * Turning one on needs its context window.
     */
    "other": ModelOption[] | null;

    /**
     * NoModelList: the provider has no model list, so models are typed in.
     */
    "no_model_list": boolean;

    /**
     * Problem is why the list couldn't be read; the models that are on are
     * still shown.
     */
    "problem"?: string;
}

/**
 * ProviderStatus is a connected provider's state, for the bottom bar
 * (SPEC 5.12).
 */
export interface ProviderStatus {
    "name": string;
    "kind": string;

    /**
     * how long it stays paused; 0 if not
     */
    "paused_ms": number;

    /**
     * background calls at once
     */
    "limit": number;

    /**
     * the limit now, halved after a rate limit
     */
    "current": number;

    /**
     * calls running now
     */
    "running": number;

    /**
     * calls waiting for a slot
     */
    "waiting": number;
    "last_problem"?: string;
}

/**
 * SearchRequest is a history search (SPEC 2.3).
 */
export interface SearchRequest {
    "query": string;

    /**
     * "" searches every chat of the project
     */
    "chat"?: id$0.Chat;

    /**
     * *Search inside words*
     */
    "substring": boolean;

    /**
     * 0 means 20; at most 100
     */
    "limit": number;
}

/**
 * SettingsView is the settings with the problems found reading them.
 */
export interface SettingsView {
    "settings": config$0.Settings;
    "problems": config$0.Problem[] | null;
}

/**
 * Started is what this start of the app used, for the settings that apply
 * at the next start: the data folder and the developer tools.
 */
export interface Started {
    /**
     * in use
     */
    "data_folder": string;

    /**
     * used when data_folder is ""
     */
    "default_data_folder": string;
    "dev_tools": boolean;

    /**
     * Moved is what moving the projects to a changed data folder did at
     * this start (SPEC 2.1); nil if the folder didn't change.
     */
    "moved": project$0.MoveResult | null;
}

/**
 * UsageLine is the tokens of one day, chat or model.
 */
export interface UsageLine {
    /**
     * YYYY-MM-DD, for a day
     */
    "day"?: string;

    /**
     * the project's name, for a chat
     */
    "project"?: string;

    /**
     * the chat's title, for a chat
     */
    "chat"?: string;

    /**
     * the catalog's name, else the model ID
     */
    "model"?: string;

    /**
     * the provider's name, for a model
     */
    "provider"?: string;

    /**
     * not read from the cache
     */
    "input": number;
    "output": number;
    "cache_read": number;
    "cache_write": number;

    /**
     * US dollars, for the tokens with a price
     */
    "cost": number;

    /**
     * tokens of models the catalog has no price for
     */
    "unpriced": number;
}

/**
 * UsageReport is *Settings → Usage* (SPEC 3.9): tokens per day, per chat
 * and per model, with the cost from the catalog prices.
 */
export interface UsageReport {
    /**
     * every day of the range, oldest first
     */
    "days": UsageLine[] | null;

    /**
     * most tokens first
     */
    "chats": UsageLine[] | null;

    /**
     * most tokens first
     */
    "models": UsageLine[] | null;
    "total": UsageLine;

    /**
     * Skipped are the projects whose chats couldn't be read, by name.
     */
    "skipped": string[] | null;
}

/**
 * WaitingItem is a chat that waits for the user, for *Waiting* in the
 * rail (SPEC 5.12).
 */
export interface WaitingItem {
    "project": id$0.Project;
    "chat": id$0.Chat;
    "title": string;
    "waiting": chat$0.Waiting;
}
