// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "../agent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as chat$0 from "../chat/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as id$0 from "../id/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "../project/models.js";

/**
 * ChatItem is a row of the chat list.
 */
export interface ChatItem {
    "chat": chat$0.Chat;

    /**
     * Status is "in a turn", "waiting for the user" or "" when idle.
     */
    "status": string;

    /**
     * the newest message; nil without messages
     */
    "last_activity"?: string | null;
}

/**
 * ChatSnapshot is a chat as it is now (Q32): its last turns, the sequence
 * number they are current at, and the turn still running. Events with a
 * lower Seq are already in it.
 */
export interface ChatSnapshot {
    "chat": chat$0.Chat;
    "messages": chat$0.Message[] | null;

    /**
     * the first turn in Messages; older ones come from Messages
     */
    "from": number;
    "seq": number;

    /**
     * the answer still streaming, a wait or a retry
     */
    "live": agent$0.Live;
}

/**
 * Object is a file in the bucket.
 */
export interface $Object {
    "key": string;
    "sha256": string;
    "mime": string;
    "size": number;
    "version": number;

    /**
     * upload, http, pipeline, agent or tool
     */
    "source": string;
    "source_url"?: string;
    "created_by": id$0.Source;
    "updated_at": string;
    "expires"?: string | null;
}

/**
 * ObjectPage is one page of a folder.
 */
export interface ObjectPage {
    "objects": $Object[] | null;

    /**
     * ending in "/"
     */
    "folders": string[] | null;

    /**
     * pass as after for the next page; "" at the end
     */
    "next": string;
}

/**
 * ObjectVersion is one version of a file.
 */
export interface ObjectVersion {
    "version": number;
    "sha256": string;
    "size": number;
    "created_by": id$0.Source;
    "created_at": string;
}

/**
 * OpenedProject is a project as the app shell needs it.
 */
export interface OpenedProject {
    "id": id$0.Project;
    "name": string;

    /**
     * the Mother chat, opened first (8.6)
     */
    "mother": id$0.Chat;

    /**
     * the approval level (8.8)
     */
    "level": string;

    /**
     * Damage is set when the project is open read-only after damage (2.7).
     */
    "damage"?: project$0.Damage | null;
}

/**
 * ProjectItem is a row of the project list.
 */
export interface ProjectItem {
    "id": id$0.Project;
    "name": string;
    "folder": string;
    "pinned": boolean;

    /**
     * nil if never opened
     */
    "last_opened"?: string | null;
    "created_at": string;
}

/**
 * ProviderStatus is a connected provider's state, for the bottom bar
 * (SPEC 5.12).
 */
export interface ProviderStatus {
    "name": string;
    "kind": string;

    /**
     * how long it stays paused; 0 if not
     */
    "paused_ms": number;

    /**
     * background calls at once
     */
    "limit": number;

    /**
     * the limit now, halved after a rate limit
     */
    "current": number;

    /**
     * calls running now
     */
    "running": number;

    /**
     * calls waiting for a slot
     */
    "waiting": number;
    "last_problem"?: string;
}

/**
 * SearchRequest is a history search (SPEC 2.3).
 */
export interface SearchRequest {
    "query": string;

    /**
     * "" searches every chat of the project
     */
    "chat"?: id$0.Chat;

    /**
     * *Search inside words*
     */
    "substring": boolean;

    /**
     * 0 means 20; at most 100
     */
    "limit": number;
}

/**
 * SettingsView is the settings with the problems found reading them.
 */
export interface SettingsView {
    "settings": config$0.Settings;
    "problems": config$0.Problem[] | null;
}
