// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProjectService is the project list and opening projects (SPEC 2.1, 2.7).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as id$0 from "../id/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "../project/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Activity is the project's work now; changes come as project:activity
 * events.
 */
export function Activity(p: id$0.Project): $CancellablePromise<project$0.Activity> {
    return $Call.ByID(1892823931, p);
}

/**
 * Create makes a project and opens it (*Create project*, 3.9).
 */
export function Create(name: string): $CancellablePromise<$models.OpenedProject> {
    return $Call.ByID(307443362, name);
}

/**
 * FolderWarning says whether the data folder is a bad place for the
 * projects, for the banner in 2.1; nil when it is fine.
 */
export function FolderWarning(): $CancellablePromise<project$0.FolderWarning | null> {
    return $Call.ByID(1765248266);
}

/**
 * List returns every project.
 */
export function List(): $CancellablePromise<$models.ProjectItem[] | null> {
    return $Call.ByID(4051584978);
}

/**
 * Open opens a project. Its notices, such as a recovery, come as
 * project:notice events.
 */
export function Open(p: id$0.Project): $CancellablePromise<$models.OpenedProject> {
    return $Call.ByID(4141360838, p);
}
