// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService is *Settings* (SPEC 5.12). P1-16 adds connecting
 * providers and usage.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Get returns the settings and the problems found in config.yaml.
 */
export function Get(): $CancellablePromise<$models.SettingsView> {
    return $Call.ByID(2239537034);
}

/**
 * Providers lists the connected providers.
 */
export function Providers(): $CancellablePromise<$models.ProviderStatus[] | null> {
    return $Call.ByID(1874244664);
}

/**
 * Save stores the settings and applies them.
 */
export function Save(next: config$0.Settings): $CancellablePromise<$models.SettingsView> {
    return $Call.ByID(2298170107, next);
}
