// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService is what the bottom bar shows about the computer (SPEC 5.12).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sysmem$0 from "../sysmem/models.js";

/**
 * Memory returns the free and total memory (8.5); the bottom bar reads it
 * about every 2 s while the window is visible.
 */
export function Memory(): $CancellablePromise<sysmem$0.Reading> {
    return $Call.ByID(1298864829);
}
