// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService is what the app asks of the computer: the memory for the
 * bottom bar and desktop notifications (SPEC 5.12, 8.8).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sysmem$0 from "../sysmem/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Memory returns the free and total memory (8.5); the bottom bar reads it
 * about every 2 s while the window is visible.
 */
export function Memory(): $CancellablePromise<sysmem$0.Reading> {
    return $Call.ByID(1298864829);
}

/**
 * Notify shows n. The frontend calls it when a chat starts to wait while
 * it isn't on screen or the window isn't focused (8.8).
 */
export function Notify(n: $models.Notification): $CancellablePromise<void> {
    return $Call.ByID(3678736191, n);
}
